steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/cloud-build-project/arnab7456/cloud-build-project:$SHORT_SHA',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/cloud-build-project/arnab7456/cloud-build-project:$SHORT_SHA',
      ]
